name: release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - lib/version.rb

permissions: {}

jobs:
  release:
    if: github.repository == 'grantbirki/lemons'
    permissions:
      contents: write
      id-token: write
      packages: write
      attestations: write
    uses: github/salsa/.github/workflows/ruby.yml@eabc30af8619f6db821dac325c6dfc85538f003c
    with:
      bootstrap_script: script/bootstrap
      build_script: script/build
      environment: release
